/*========= begin authActions   ===========*/
export const REQUEST_AUTH = 'REQUEST_AUTH';
export const RECEIVE_AUTH = 'RECEIVE_AUTH';

export const SAVE_AUTH = 'SAVE_AUTH';
export const DELETE_AUTH = 'DELETE_AUTH';

export const REQUEST_ACCESS_KEYS = 'REQUEST_ACCESS_KEYS';
export const RECEIVE_ACCESS_KEYS = 'RECEIVE_ACCESS_KEYS';

export const REQUEST_REMOVE_ACCESS_KEY = 'REQUEST_REMOVE_ACCESS_KEY';
export const RECEIVE_REMOVE_ACCESS_KEY = 'RECEIVE_REMOVE_ACCESS_KEY';

export const REQUEST_PATCH_ACCESS_KEY = 'REQUEST_PATCH_ACCESS_KEY';
export const RECEIVE_PATCH_ACCESS_KEY = 'RECEIVE_PATCH_ACCESS_KEY';

export const REQUEST_CREATE_ACCESS_KEY = 'REQUEST_CREATE_ACCESS_KEY';
export const RECEIVE_CREATE_ACCESS_KEY = 'RECEIVE_CREATE_ACCESS_KEY';

export const OPEN_POP_SHOW_KEY = 'OPEN_POP_SHOW_KEY';
export const CLOSE_POP_SHOW_KEY = 'CLOSE_POP_SHOW_KEY';
/*========= end authActions   ===========*/

/*========= begin usersActions   ===========*/
export const USER_LOGOUT = 'USER_LOGOUT';
export const LOGIN_CHANGE_ACCOUNT_INPUT = 'LOGIN_CHANGE_ACCOUNT_INPUT';
export const LOGIN_CHANGE_PASSWORD_INPUT = 'LOGIN_CHANGE_PASSWORD_INPUT';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';
export const RECEIVE_LOGIN_ERROR = 'RECEIVE_LOGIN_ERROR';
/*========= end usersActions   ===========*/

/*========= begin registersActions   ===========*/
export const REGISTER_CHANGE_EMAIL_INPUT = 'REGISTER_CHANGE_EMAIL_INPUT';

export const REQUEST_REGISTER_CHECK_EMAIL = 'REQUEST_REGISTER_CHECK_EMAIL';
export const RECEIVE_REGISTER_CHECK_EMAIL = 'RECEIVE_REGISTER_CHECK_EMAIL';
export const RECEIVE_REGISTER_CHECK_EMAIL_ERROR = 'RECEIVE_REGISTER_CHECK_EMAIL_ERROR';

export const REGISTER_CHANGE_VALIDATE_CODE_INPUT = 'REGISTER_CHANGE_VALIDATE_CODE_INPUT';

export const REQUEST_REGISTER_SEND_VALIDATE_CODE = 'REQUEST_REGISTER_SEND_VALIDATE_CODE';
export const RECEIVE_REGISTER_SEND_VALIDATE_CODE = 'RECEIVE_REGISTER_SEND_VALIDATE_CODE';
export const RECEIVE_REGISTER_SEND_VALIDATE_CODE_ERROR = 'RECEIVE_REGISTER_SEND_VALIDATE_CODE_ERROR';

export const REQUEST_REGISTER_CHECK_CODE_EXISTS = 'REQUEST_REGISTER_CHECK_CODE_EXISTS';
export const RECEIVE_REGISTER_CHECK_CODE_EXISTS = 'RECEIVE_REGISTER_CHECK_CODE_EXISTS';
export const RECEIVE_REGISTER_CHECK_CODE_EXISTS_ERROR = 'RECEIVE_REGISTER_CHECK_CODE_EXISTS_ERROR';

export const REGISTER_CHANGE_PASSWORD_INPUT = 'REGISTER_CHANGE_PASSWORD_INPUT';
export const REGISTER_CHANGE_PASSWORD_CONFIRM_INPUT = 'REGISTER_CHANGE_PASSWORD_CONFIRM_INPUT';

export const REQUEST_REGISTER = 'REQUEST_REGISTER';
export const RECEIVE_REGISTER = 'RECEIVE_REGISTER';
export const RECEIVE_REGISTER_ERROR = 'RECEIVE_REGISTER_ERROR';

export const RECEIVE_REGISTER_CLEAN = 'RECEIVE_REGISTER_CLEAN';
/*========= end registersActions   ===========*/

/*========= begin routesActions   ===========*/
export const SET_BACK_HISTORY = 'SET_BACK_HISTORY';
export const GO_BACK_HISTORY = 'GO_BACK_HISTORY';
export const SHOW_HOME = 'SHOW_HOME';
export const SHOW_LOGIN = 'SHOW_LOGIN';
/*========= end routesActions   ===========*/

/*========= begin productsActions ===========*/
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';

/*========= end productsActions   ===========*/
